#:schema node_modules/wrangler/config-schema.json
name = "check-health-rabbitmq"
main = "src/index.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

[vars]
RABBITMQ_API_URL = "https://armadillo.rmq.cloudamqp.com/api/queues/gxylgqlb"
AUTH_RABBITMQ = "gxylgqlb:OWeSHYsGOtgehoHdMHBwkbnvUOHLZQCI"
